---
- name: Adds user 
  hosts: all
  become: yes
  become_method: sudo 
  connection: ssh 
  gather_facts: no 
  tasks:
    - name: Add user bob 
      user:
        name: bob
        state: present   
        comment: "Developer" 
        generate_ssh_key: yes
        uid: 1040
        group: dev
